-- QuizCloud complete Supabase schema
-- Run this in a fresh Supabase project, or use it as the reference migration for the existing project.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text unique not null,
  role text not null default 'user' check (role in ('user','admin')),
  plan text not null default 'free' check (plan in ('free','premium')),
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.education_levels (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.streams (
  id bigint generated by default as identity primary key,
  education_level_id bigint not null references public.education_levels(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  unique (education_level_id, name)
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  stream_id bigint not null references public.streams(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  unique (stream_id, name)
);

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  unique (subject_id, name)
);

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  category text not null,
  difficulty text not null,
  total_questions integer not null default 0,
  time_limit integer not null default 10,
  subject_id bigint references public.subjects(id) on delete set null,
  topic_id bigint references public.topics(id) on delete set null,
  access_type text not null default 'free' check (access_type in ('free','premium')),
  published boolean not null default true,
  premium_features jsonb not null default '{"explanations":false,"hints":false,"negative_marking":false,"advanced_analytics":false,"mock_exam":false,"certificate":false}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  question_text text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null check (upper(correct_answer) in ('A','B','C','D')),
  explanation text default '',
  marks integer not null default 1,
  negative_marks numeric(5,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  score integer not null default 0,
  total_questions integer not null,
  percentage numeric(5,2) not null default 0,
  completed_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  payment_id text unique,
  email text not null,
  name text not null default '',
  amount integer not null check (amount > 0),
  currency text not null default 'INR',
  status text not null default 'created' check (status in ('created','paid','failed')),
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.user_plans (
  email text primary key,
  name text not null default '',
  plan text not null default 'free' check (plan in ('free','premium')),
  razorpay_order_id text,
  updated_at timestamptz not null default now()
);

-- Compatibility columns for older databases
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists plan text not null default 'free';
alter table public.quizzes add column if not exists subject_id bigint references public.subjects(id) on delete set null;
alter table public.quizzes add column if not exists topic_id bigint references public.topics(id) on delete set null;
alter table public.quizzes add column if not exists access_type text not null default 'free';
alter table public.quizzes add column if not exists published boolean not null default true;
alter table public.quizzes add column if not exists total_questions integer not null default 0;
alter table public.quizzes add column if not exists time_limit integer not null default 10;
alter table public.quizzes add column if not exists premium_features jsonb not null default '{"explanations":false,"hints":false,"negative_marking":false,"advanced_analytics":false,"mock_exam":false,"certificate":false}'::jsonb;
alter table public.questions add column if not exists explanation text default '';
alter table public.questions add column if not exists marks integer not null default 1;
alter table public.questions add column if not exists negative_marks numeric(5,2) not null default 0;

create unique index if not exists education_levels_name_uidx on public.education_levels(name);
create unique index if not exists streams_level_name_uidx on public.streams(education_level_id,name);
create unique index if not exists subjects_stream_name_uidx on public.subjects(stream_id,name);
create unique index if not exists topics_subject_name_uidx on public.topics(subject_id,name);

-- Allow admin accounts. Older versions used a user-only constraint.
do $$
declare c record;
begin
  for c in select conname from pg_constraint where conrelid = 'public.profiles'::regclass and contype = 'c' and pg_get_constraintdef(oid) ilike '%role%' loop
    execute format('alter table public.profiles drop constraint if exists %I', c.conname);
  end loop;
exception when undefined_table then null;
end $$;
alter table public.profiles add constraint profiles_role_check check (role in ('user','admin'));

-- Keep profile rows in sync with Supabase Auth.
create or replace function public.handle_new_user_profile()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role, plan)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'full_name',''), 'user', 'free')
  on conflict (id) do update set email = excluded.email;
  insert into public.user_plans (email, name, plan)
  values (new.email, coalesce(new.raw_user_meta_data ->> 'full_name',''), 'free')
  on conflict (email) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile after insert on auth.users for each row execute function public.handle_new_user_profile();

-- Seed common learning paths if missing.
insert into public.education_levels(name, description) values
('Higher School','Class 6 to Class 10'),
('PUC / Higher Secondary','Higher secondary streams such as PCMB'),
('UG','Undergraduate courses'),
('PG','Postgraduate courses')
on conflict (name) do nothing;

-- RLS: the backend uses the service role for writes and protected reads.
alter table public.profiles enable row level security;
alter table public.education_levels enable row level security;
alter table public.streams enable row level security;
alter table public.subjects enable row level security;
alter table public.topics enable row level security;
alter table public.quizzes enable row level security;
alter table public.questions enable row level security;
alter table public.results enable row level security;
alter table public.payments enable row level security;
alter table public.user_plans enable row level security;

drop policy if exists "profiles select own" on public.profiles;
create policy "profiles select own" on public.profiles for select to authenticated using (auth.uid() = id);

drop policy if exists "public education levels read" on public.education_levels;
create policy "public education levels read" on public.education_levels for select using (true);
drop policy if exists "public streams read" on public.streams;
create policy "public streams read" on public.streams for select using (true);
drop policy if exists "public subjects read" on public.subjects;
create policy "public subjects read" on public.subjects for select using (true);
drop policy if exists "public topics read" on public.topics;
create policy "public topics read" on public.topics for select using (true);
drop policy if exists "public quizzes read" on public.quizzes;
create policy "public quizzes read" on public.quizzes for select using (published = true);
drop policy if exists "public questions read" on public.questions;
create policy "public questions read" on public.questions for select using (true);
drop policy if exists "results own read" on public.results;
create policy "results own read" on public.results for select to authenticated using (auth.uid() = user_id);

-- IMPORTANT: promote your own admin account after creating it:
-- update public.profiles set role = 'admin' where lower(email) = lower('YOUR_ADMIN_EMAIL');
